# Generated by Django 3.2 on 2021-05-03 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название заметки')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
